CREATE TABLE `api_parameter` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '【编号】自增长编号',
  `parent_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '【上级类型】application,interface,parameter',
  `parent_id` bigint(20) NOT NULL COMMENT '【上级ID】',
  `name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '【名称】上级+名称 唯一',
  `alias` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '【别称】json array 别称,多个可用参数值将映射到第一个区配的值如 参数名称id,别称uid,gid,uuid传入id=&uid=&gid=100&uuid=200,最后参数id取值为100 ',
  `title` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '【标题】',
  `sort` int(11) NOT NULL DEFAULT '0' COMMENT '【排序】',
  `position` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'body' COMMENT '【取值位置】query header cookie form body 默认"body" , 为子参数不填,时同上级',
  `default_value` varchar(4000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '【默认值】',
  `data_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT 'string' COMMENT '【数据类型】string,int,long,double,boolean,date,object',
  `is_array` int(2) NOT NULL DEFAULT '0' COMMENT '【是否数组】0否 1是',
  `is_required` int(2) NOT NULL DEFAULT '0' COMMENT '【是否必填】0否 1是',
  `is_hidden` int(2) NOT NULL DEFAULT '0' COMMENT '【是否隐藏】0否 1是 隐藏时文档中不显示参数,但可以传入 ',
  `is_read_only` int(2) NOT NULL DEFAULT '0' COMMENT '【是否只读】0否 1是 只读时不能传入参数,只取默认值',
  `examples` varchar(4000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '【示例值】json array 支持mock变量',
  `validations` varchar(4000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '【参数验证】json Validation格式',
  `status` int(2) NOT NULL DEFAULT '0' COMMENT '【状态】0正常 1停用',
  `gmt_create` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '【创建时间】',
  `gmt_modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '【修改时间】',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_p_name` (`parent_type`,`parent_id`,`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='【接口参数表】';